### PR TITLE
Update extensions

### PR DESCRIPTION
**Pull request by roypaulin**
The following changes were made:
- Update the extensions to work on jupyterlab4.0.x
- Update vertica-start cmd so that now if verticapylab is already running, it will open it in the browser
- Fix the TEST_MODE on MacOS

### CODE REVIEW

**Comment by roypaulin** [comment]
@mail4umar can intensively test this? I will like you to build the image and and try the commands and report any errors so that I can fix them.

**Comment by roypaulin** [comment]
@oualib I was not able to add back the vsql/admintools buttons. I tried to put all of them in a single extensions but it did not work. Here are our options:
-  Add them later. For that we would need to create another extension. I don't think it is worth the effort as it will balloon the container, without offering much.
- Users can still use vsql/admintools through the `Terminal` button in jupyterlab all the need is to click on the button and when the terminal open up, run vsql/admintools
- Create a separate extension but, but not include it in the image, users could install it at run time if they want. We cannot put everything in the image
- Never put them back. I think we should leverage voila to build more web-based extensions and just add buttons to redirect to those web pages. This approach is light and relies on notebooks that don't need to be stored in the image, so it can really scale.

**Comment by mail4umar** [comment]
@roypaulin Why are we still keeping the folder "extensions"?

**Comment by roypaulin** [comment]
> @roypaulin Why are we still keeping the folder "extensions"?

It is just needed as a code reference to write the extensions in `extensions-v2`, after this PR it can be removed.

**Review by mail4umar — APPROVED** [review]

**Pull request merged**
