### PR TITLE
Update QueryProfiler Tree Page - Advanced Display Options + Plots

### PR DESCRIPTION
**Pull request by mail4umar**
Added advanced display options
Also added tab for plots

### CODE REVIEW

**Comment by roypaulin** [comment]
Are these settings for the QueryProfilerInterface or Verticapy in general?

**Comment by mail4umar** [comment]
> Are these settings for the QueryProfilerInterface or Verticapy in general?

The entire environment. So it will include everything inside the container jupyterlab.

**Comment by roypaulin** [comment]
> > Are these settings for the QueryProfilerInterface or Verticapy in general?
> 
> The entire environment. So it will include everything inside the container jupyterlab.

So the maximum number of rows is for what exactly? a vdataframe? anything else? just trying to understand.

**Comment by mail4umar** [comment]
> > > Are these settings for the QueryProfilerInterface or Verticapy in general?
> > 
> > 
> > The entire environment. So it will include everything inside the container jupyterlab.
> 
> So the maximum number of rows is for what exactly? a vdataframe? anything else? just trying to understand.

Yes, only for vDataFrame.

**Review by roypaulin — APPROVED** [review]
Let the user know what is going to be changed by these settings.

**Pull request merged**
